BigWigsMods/LittleWigs

Legion/NeltharionsLair/Trash.lua
Legion/NeltharionsLair/modules.xml

Adds a Trash module to Neltharion's Lair and an Avalanche warning to the Breaker mobs.
It's pretty important to walk out of it on higher M+
For some reason there are multiple IDs of Breaker mobs but I've included them all.

Added Avalanche warning for Neltharion's Lair Trash

---

Legion/Karazhan/Moroes.lua

1x LittleWigs\Legion\Karazhan\Moroes.lua:177: attempt to call field 'on' (a string value)
LittleWigs\Legion\Karazhan\Moroes.lua:177: in function `?'
BigWigs_Core\BossPrototype.lua:391: in function <BigWigs_Core\BossPrototype.lua:358>

Karazhan/Moroes: Fix minor bug

---

Legion/VaultOfTheWardens/Tormentorum.lua

Commits' messages are more descriptive.
Went with `"Urgent"` and `"Warning"` for "Flesh to Stone" because that seems to be what this module uses for abilities of summoned adds.

VaultOfTheWardens/Tormentorum: handle "Flesh to Stone" and "Shadow Crash", refactor UNIT_HEALTH_FREQUENT

---

Legion/Karazhan/Curator.lua

People often reset him in M+ to clear the trash in his room.

Karazhan/Curator: added a respawn timer

---

Legion/Karazhan/Trash.lua

Karazhan/Trash: do not warn about DK-controlled units casting "Shield Smash" and "Banshee Wail", closes #156

---

Legion/SeatOfTheTriumvirate/Lura.lua

The zones that people need to stand in become visible only after the cast goes through. If the mob dies while casting, nothing needs to be soaked.

SeatOfTheTriumvirate/Lura: changed warnings for "Fragment of Despair" to use SPELL_CAST_SUCCESS instead, adjusted CD bars slightly

---

Legion/Karazhan/Moroes.lua

This mechanic consistently targets the healer, so, unless you have a shadow priest or are running with multiple healers(?), dispelling it is not the way to go (it stuns its target, at least on Mythic). Fortunately, it can be interrupted. And, AFAIK, you have about 1s to interrupt it before it actually starts channeling, so this also gives you an earlier warning.

Karazhan/Moroes: warn when Mana Drain is being casted rather than when it's already applied

---

Cataclysm/ThroneTides/Locales/deDE.lua
Cataclysm/ThroneTides/Locales/esES.lua
Cataclysm/ThroneTides/Locales/frFR.lua
Cataclysm/ThroneTides/Locales/itIT.lua
Cataclysm/ThroneTides/Locales/koKR.lua
Cataclysm/ThroneTides/Locales/ptBR.lua
Cataclysm/ThroneTides/Locales/ruRU.lua
Cataclysm/ThroneTides/Locales/zhCN.lua
Cataclysm/ThroneTides/Locales/zhTW.lua
Cataclysm/ThroneTides/Mindbender.lua
Cataclysm/ThroneTides/Naz'jar.lua
Cataclysm/ThroneTides/Ozumat.lua
Cataclysm/ThroneTides/Ulthok.lua
Cataclysm/ThroneTides/locales.xml
Cataclysm/ThroneTides/modules.xml
modules.xml

- Added a module for Ozumat that includes an option to automatically start the encounter, a timer for Stage 1 and tracking of adds killed in Stage 2.
- Mindbender: there's a boss unit now, so it's being used for HP tracking instead of target/focus.
- Naz'jar: if "Waterspout" ends early, its bar gets removed.
- Ulthok: now warns those who can dispel curses about "Curse of Fatigue", also warns its victims.
- All of them now use ENCOUNTER_START and ENCOUNTER_END and have timers for their respawns.

Cataclysm/ThroneOfTheTides: various improvements

---

Legion/HallsOfValor/God-KingSkovald.lua
Legion/SeatOfTheTriumvirate/Zuraal.lua

Shouldn't really happen, but what if. We are checking against `nil` anyway.

Provide 2nd arg to :GetBossModule() calls to prevent Lua errors on failure

---

Legion/MawOfSouls/Helya.lua

Hi,
Currently Brackwater Barrage on Helya has an associated severity of Info. I believe the ability should be presented as an Alarm (similar to corrupted below, as they do similar amounts of damage). To me, "Alarm" always feels like something I need to look at immediately, and indicates something like one shot mechanics, or something that will wipe the group. I think this is a better indication of the severity of the ability.

MawOfSouls/Helya: Change 'Brackwater Barrage' sound from 'Info' to 'Alarm'

---

TBC/TheBotanica/WarpSplinter.lua

The spell ID 32130 for the old "Heal" spell is no longer in the
game, so use the spell ID 2060 for the priest's current Heal spell.
This fixes the "Heal on BOSS" string used on the bar.

TBC/TheBotanica/WarpSplinter: Fix spell ID for "Heal".

---

modules.xml

Looks like the King's Rest locales.xml is commented out by mistake. The locale files are all there in BfA/KingsRest/Locales

BfA/KingsRest: Uncomment locales.xml

---

BfA/Freehold/Kragg.lua
BfA/Freehold/Options/Sounds.lua

- Fix Stage 2 initial timers and message
- Remove timer for Revitalizing Brew since it's cast at boss health percentages
- Add respawn timer

BfA/Freehold/Kragg: Fix Stage 2 initial timers and message

---

BfA/Freehold/Booty.lua
BfA/Freehold/Sweete.lua

Sweete: The add applies the fixate aura to itself as well as the target
Booty: The timer alternates between 20 and 30, but it's random which one it starts with

BfA/Freehold: Fix Sweete's Fixate message appearing twice, and fix Booty's Shark Toss timer

---

BfA/SiegeOfBoralus/Brainbridge.lua
BfA/SiegeOfBoralus/Darkfathom.lua
BfA/SiegeOfBoralus/Locales/deDE.lua
BfA/SiegeOfBoralus/Locales/esES.lua
BfA/SiegeOfBoralus/Locales/frFR.lua
BfA/SiegeOfBoralus/Locales/itIT.lua
BfA/SiegeOfBoralus/Locales/koKR.lua
BfA/SiegeOfBoralus/Locales/ptBR.lua
BfA/SiegeOfBoralus/Locales/ruRU.lua
BfA/SiegeOfBoralus/Locales/zhCN.lua
BfA/SiegeOfBoralus/Locales/zhTW.lua
BfA/SiegeOfBoralus/Lockwood.lua
BfA/SiegeOfBoralus/Options/Colors.lua
BfA/SiegeOfBoralus/Options/Sounds.lua
BfA/SiegeOfBoralus/Redhook.lua
BfA/SiegeOfBoralus/Trash.lua
BfA/SiegeOfBoralus/Viqgoth.lua

Bainbridge/Redhook:
- Add timer for Heavy Ordnance explosion
- Add remaining bomb count to Heavy Ordnance message
- Add Heavy Ordnance message for players and adds
- Remove add timer since they seem to spawn at health percentages
Lockwood:
- Improve timers for Clear the Deck, Withdraw, and Broadside
- Remove Crimson Swipe timer, and make messages tank only (they're just spam for non-tanks pretty much)
- Add Gut Shot target message
Darkfathom:
- Improve timers for Crashing Tide and Tidal Surge
- Add timer for Break Water damage (cast bar)
Viqgoth:
- Use TargetsMessage for Putrid Waters
- Add Hull Cracker message and sound
- Add Repair cast bar for the cannons
- Fix Demolishing Terror timer
Trash:
- Add Molten Slug personal messages when targeted

BfA/SiegeOfBoralus: Improve boss timers and messages

---

BfA/ShrineOfTheStorm/Aqusirr.lua
BfA/ShrineOfTheStorm/Council.lua
BfA/ShrineOfTheStorm/Options/Colors.lua
BfA/ShrineOfTheStorm/Options/Sounds.lua
BfA/ShrineOfTheStorm/Stormsong.lua

**Aqusirr**
- Add stage messages
- Add timer for Choking Brine, Surging Rush, Undertow, and Grasp from the Depths
- Improve target messages
**Council**
- Add Blessing of Ironsides timer and message
**Stormsong**
- Add Mind Rend target message

BfA/ShrineOfTheStorm: Improve timers and messages for Aqu'sirr, Council, and Stormsong

---

BfA/Underrot/Abomination.lua
BfA/Underrot/Crawg.lua
BfA/Underrot/Leaxa.lua
BfA/Underrot/Locales/deDE.lua
BfA/Underrot/Locales/esES.lua
BfA/Underrot/Locales/frFR.lua
BfA/Underrot/Locales/itIT.lua
BfA/Underrot/Locales/koKR.lua
BfA/Underrot/Locales/ptBR.lua
BfA/Underrot/Locales/ruRU.lua
BfA/Underrot/Locales/zhCN.lua
BfA/Underrot/Locales/zhTW.lua
BfA/Underrot/Options/Colors.lua
BfA/Underrot/Zancha.lua

closes #422 
Leaxa:
- Remove death message for adds. It was left over from before the hotfix that changed the number of adds spawned to always be 1.
Crawg:
- Rename the first bar after each tantrum to "Charge or Indigestion" since it's random
- Improve accuracy of all timers
Zancha:
- Improve timers for Volatile Pods and Festering Harvest
Abomination:
- Add target bar for Cleansing Light

BfA/Underrot: Improve timers for all bosses

---

BfA/Underrot/Options/Colors.lua
BfA/Underrot/Options/Sounds.lua
BfA/Underrot/Trash.lua

It's not worth interrupting (there are more important things) and it's really spammy.

BfA/Underrot/Trash: Remove Wave of Decay cast message

---

BfA/Freehold/Kragg.lua
BfA/Freehold/Options/Colors.lua
BfA/Freehold/Options/Sounds.lua

BfA/Freehold/Kragg: Add Vile Bombardment message and fix timer for the remainder of the fight in rare cases where the bird charges sooner than normal

BfA/Freehold/Kragg: Add Vile Bombardment message and fix timer

---

BfA/Freehold/Booty.lua
BfA/Freehold/Captains.lua
BfA/Freehold/Kragg.lua
BfA/Freehold/Options/Colors.lua
BfA/Freehold/Options/Sounds.lua
BfA/Freehold/Sweete.lua

Kragg:
- Add initial dive bomb timer
- Throttle Vile Bombardment damage for the first tick after it hits the ground. The first tick isn't needed now that there's a message for when Vile Bombardment is fired.
Captains:
- Add Captain Jolly
- Add personal messages and on boss messages for brews
- Improve initial timers
- Add respawn time
Booty:
- Add respawn time
Sweete:
- Add respawn time

BfA/Freehold: Add Captain Jolly and add messages when brews are applied to bosses

---

BfA/TheMotherlode/CrowdPummeler.lua
BfA/TheMotherlode/Options/Colors.lua
BfA/TheMotherlode/Options/Sounds.lua
BfA/TheMotherlode/Razzdunk.lua
BfA/TheMotherlode/Rixxa.lua
BfA/TheMotherlode/Tikali.lua
BfA/TheMotherlode/Trash.lua

CrowdPummeler:
- Add Throw Coin message
- Add Pay to Win stack message
Tikali:
- Throttle Raging Gaze say message
Rixxa:
- Add Azerite Catalyst
- Fix Chemical Burn targetsmessage
- Reset Chemical Burn counter on pull
Razzdunk:
- Stop micro missiles cast bar when intermission starts
Trash:
- Remove Transmute Enemy to Goo targetbar

BfA/TheMotherlode: Add Throw Coins, Pay to Win, and Azerite Catalyst

---

BfA/WaycrestManor/Goliath.lua
BfA/WaycrestManor/GorakTul.lua
BfA/WaycrestManor/Heartsbane.lua
BfA/WaycrestManor/Locales/deDE.lua
BfA/WaycrestManor/Locales/esES.lua
BfA/WaycrestManor/Locales/frFR.lua
BfA/WaycrestManor/Locales/itIT.lua
BfA/WaycrestManor/Locales/koKR.lua
BfA/WaycrestManor/Locales/ptBR.lua
BfA/WaycrestManor/Locales/ruRU.lua
BfA/WaycrestManor/Locales/zhCN.lua
BfA/WaycrestManor/Locales/zhTW.lua
BfA/WaycrestManor/Options/Colors.lua
BfA/WaycrestManor/Options/Sounds.lua
BfA/WaycrestManor/Raal.lua
BfA/WaycrestManor/Trash.lua
BfA/WaycrestManor/Waycrest.lua

Heartsbane:
- Add respawn time
Raal:
- Add respawn time
- Add stack count to Consumed Servant message
Waycrest:
- Add respawn time
- Add Virulent Pathogen targetsmessage and proximity
- Move warning for Discordant Cadenza to the end of the cast
- Add Wracking Chord timer
- Add message and timer when Lady Waycrest is going to become active
GorakTul:
- Add respawn time
- Add warning when an add is killed
- Only show Darkened Lightning message for interrupters
- Improve timers
- Add Death Lens target message
Trash:
- Add Effigy Reconstruction
- Throttle Dinner Bell, Retch, Shrapnel Trap, Severing Serpent, and Infected Thorn

BfA/WaycrestManor: Improvements

---

BfA/SiegeOfBoralus/Brainbridge.lua
BfA/SiegeOfBoralus/Locales/deDE.lua
BfA/SiegeOfBoralus/Locales/esES.lua
BfA/SiegeOfBoralus/Locales/frFR.lua
BfA/SiegeOfBoralus/Locales/itIT.lua
BfA/SiegeOfBoralus/Locales/koKR.lua
BfA/SiegeOfBoralus/Locales/ptBR.lua
BfA/SiegeOfBoralus/Locales/ruRU.lua
BfA/SiegeOfBoralus/Locales/zhCN.lua
BfA/SiegeOfBoralus/Locales/zhTW.lua
BfA/SiegeOfBoralus/Options/Colors.lua
BfA/SiegeOfBoralus/Options/Sounds.lua
BfA/SiegeOfBoralus/Redhook.lua
BfA/SiegeOfBoralus/Trash.lua
BfA/SiegeOfBoralus/Viqgoth.lua

Brainbridge/Redhook:
- Add respawn time
Viqgoth:
- Add respawn time
- Add Demolishing Terror count
- Stop Demolishing Terror bars and messages after 5. They stop spawning but the spawn spell is still cast.
Trash:
- Stop Savage Tempest bar on death
- Add Banana Rampage
- Add Stinging Venom Coating

BfA/SiegeOfBoralus: Add Demolishing Terror count and more trash abilities

---

BfA/ShrineOfTheStorm/Council.lua
BfA/ShrineOfTheStorm/Options/Colors.lua
BfA/ShrineOfTheStorm/Options/Sounds.lua
BfA/ShrineOfTheStorm/Stormsong.lua

closes #344 
The Blessing of the Tempest warning only displays for players near the boss, so ranged won't get warnings about dodging tornadoes in melee.
Council:
- Add Blessing of the Tempest
- Improve timers
- Add respawn time
- Adjust colors since almost everything was yellow
Stormsong:
- Add respawn time

BfA/ShrineOfTheStorm/Council: Add Blessing of the Tempest

---

BfA/Mechagon/KUJ0.lua
BfA/Mechagon/KingMechagon.lua
BfA/Mechagon/MachinistsGarden.lua
BfA/Mechagon/OppressionUnit.lua
BfA/Mechagon/Options/Colors.lua
BfA/Mechagon/Options/Sounds.lua
BfA/Mechagon/Trash.lua
BfA/Mechagon/TrixieNaeno.lua
BfA/Mechagon/TussleTonks.lua

**TrixieNaeno**
- Add Roadkill timer
- Add Bolt Buster timer
**OppressionUnit**
- Fix reinforcement relay timer
- Add Fulminating Burst (hard mode)
**TussleTonks**
- Fix Maximum Thrust spell id
- Throttle Platinum Plating message
**KUJ0**
- Add Explosive Leap proximity
**MachinistsGarden**
- Fix timers
**KingMechagon**
- Fix timers
- Add H.A.R.D.M.O.D.E. timer
**Trash**
- Add Junkyard D.0.G.

BfA/Mechagon: Fix timers and add hard mode timers

---

BfA/ShrineOfTheStorm/Trash.lua

Prints when more than one void seed is active at a time

BfA/ShrineOfTheStorm/Trash: Add debug message for Void Seed

---

BfA/ShrineOfTheStorm/Aqusirr.lua
BfA/ShrineOfTheStorm/Stormsong.lua

You don't have to mouse over or target the NPCs that do the RP in order to start the RP, so the module is frequently not enabled when the RP starts. Instead, enable on the trash pack before the boss.

BfA/ShrineOfTheStorm: Fix warmup timers

---

BfA/WaycrestManor/Heartsbane.lua
BfA/WaycrestManor/Options/Colors.lua
BfA/WaycrestManor/Options/Sounds.lua

- Add Soul Manipulation timer and cast bar
- Add timer for Unstable Runic Marks beyond the first
- Move skull marker when the 99% damage reduction is removed
- Reorder functions so abilities for the same boss are together

BfA/WaycrestManor/Heartsbane: Improve timers

---

BfA/ShrineOfTheStorm/Options/Colors.lua
BfA/ShrineOfTheStorm/Options/Sounds.lua
BfA/ShrineOfTheStorm/Stormsong.lua

Looks like on higher M+ keys people have to dive into the water (Twisting Void) in order to handle the MC mechanic since the orbs do not deal enough damage.

ShrineOfTheStorm/Stormsong: Add a bar for Surrender to the Void, a personal message for Ancient Mindbender's removal, warnings for Twisting Void

---

.pkgmeta
LittleWigs.toc
modules.xml

I don't think loader needs any changes. Kinda forgot about this after SL launched >.>

Split out BfA modules

---

Shadowlands/Plaguefall/Trash.lua

I think it would be useful to have https://www.wowhead.com/spell=327233/belch-plague (spell id per my logs) registered on the Plaguebelcher trash mob in Plaguefall, since the slimes usually need to be slowed or cc'ed.
Note that this spell has a different id than Globgrog's Beckon Slime.
I created this PR in my browser using GitHub's edit function -- I haven't tested the Lua and I'm not sure if anything else needs to be changed to register this spell. It would also be lovely to have this spoken aloud by BigWigs_Voice -- will that generate automatically?

Shadowlands/Plaguefall/Trash: Add warnings for "Beckon Slime"

---

Shadowlands/Plaguefall/Locales/deDE.lua
Shadowlands/Plaguefall/Locales/esES.lua
Shadowlands/Plaguefall/Locales/frFR.lua
Shadowlands/Plaguefall/Locales/itIT.lua
Shadowlands/Plaguefall/Locales/koKR.lua
Shadowlands/Plaguefall/Locales/ptBR.lua
Shadowlands/Plaguefall/Locales/ruRU.lua
Shadowlands/Plaguefall/Locales/zhCN.lua
Shadowlands/Plaguefall/Locales/zhTW.lua
Shadowlands/Plaguefall/Trash.lua

This adds https://www.wowhead.com/spell=328400/stealthlings
Stealthlings need revealing by a mobile class with AoE, and/or CC'ing e.g. with Ursols Vortex or Binding Shot, so I think they're worth adding to LittleWigs for sure.
Untested, but ID is per my logs, and it's the same implementation as Enveloping Webbing.
I wasn't sure about the color and sound. I went with red and long, since Enveloping Webbing already uses alarm.

Shadowlands/Plaguefall/Trash: Warn when Stealthlings spawn

---

Shadowlands/TheaterOfPain/Trash.lua

Death Knights can Control Undead several mobs in this dungeon which have spell alerts. We don't need to show alerts for friendly casts.

Shadowlands/TheaterOfPain/Trash: don't alert for MC'd casts

---

Shadowlands/TazaveshTheVeiledMarket/Trash.lua

Refraction Shield can be applied out of combat, in particular it sometimes spams alerts when you teleport back and forth between the two entrances.

Shadowlands/TazaveshTheVeiledMarket/Trash: prevent out of combat alerts

---

Shadowlands/Plaguefall/DominaVenomblade.lua

No need to alert for DPS who cannot dispel poisons.

Shadowlands/Plaguefall/DominaVenomblade: Scope Cytotoxic Slash

---

Shadowlands/Plaguefall/Options/Colors.lua
Shadowlands/Plaguefall/Options/Sounds.lua
Shadowlands/Plaguefall/Trash.lua

- Gripping Infection can also be dispelled by movement dispellers. (Fun fact, all movement dispellers are also disease dispellers until Dragonflight at least).
- Withering Filth has been bugged since 9.0 and puts a targeting circle on the tank but then leaps to the closest player instead, making both the Blizzard graphic and the LittleWigs say unreliable.

Shadowlands/Plaguefall/Trash: Scope dispels, remove broken Withering Filth target detection

---

Shadowlands/TheNecroticWake/Amarth.lua
Shadowlands/TheNecroticWake/Locales/deDE.lua
Shadowlands/TheNecroticWake/Locales/esES.lua
Shadowlands/TheNecroticWake/Locales/frFR.lua
Shadowlands/TheNecroticWake/Locales/itIT.lua
Shadowlands/TheNecroticWake/Locales/koKR.lua
Shadowlands/TheNecroticWake/Locales/ptBR.lua
Shadowlands/TheNecroticWake/Locales/ruRU.lua
Shadowlands/TheNecroticWake/Locales/zhCN.lua
Shadowlands/TheNecroticWake/Locales/zhTW.lua
Shadowlands/TheNecroticWake/Trash.lua

- 30s respawn timer
- 25s warmup timer
- Land of the Dead does not have a SPELL_CAST_START event, it's a channel with an invisible buff
This resolves half of #561

Shadowlands/TheNecroticWake/Amarth: Respawn, Warmup, Land of the Dead

---

Shadowlands/SanguineDepths/Trash.lua

Barbed Shackles application scoped to movement dispellers, self, and healers.

Shadowlands/SanguineDepths/Trash: Restrictions for Barbed Shackles warning

---

Shadowlands/TazaveshTheVeiledMarket/Options/Colors.lua
Shadowlands/TazaveshTheVeiledMarket/Trash.lua

Adds an additional alert on Lockdown application for magic and movement dispellers.

Shadowlands/TazaveshTheVeiledMarket/Trash: Lockdown dispel alert

---

Shadowlands/Plaguefall/Locales/deDE.lua
Shadowlands/Plaguefall/Locales/esES.lua
Shadowlands/Plaguefall/Locales/frFR.lua
Shadowlands/Plaguefall/Locales/itIT.lua
Shadowlands/Plaguefall/Locales/koKR.lua
Shadowlands/Plaguefall/Locales/ptBR.lua
Shadowlands/Plaguefall/Locales/ruRU.lua
Shadowlands/Plaguefall/Locales/zhCN.lua
Shadowlands/Plaguefall/Locales/zhTW.lua
Shadowlands/Plaguefall/Options/Colors.lua
Shadowlands/Plaguefall/Options/Sounds.lua
Shadowlands/Plaguefall/Trash.lua

Show crushing embrace alert for healers and the target.
Depending on which version of Slime Tentacle is the caster, additionally show an alert for whoever can stop the cast.

Shadowlands/Plaguefall/Trash: Crushing Embrace, Vile Spit

---

Shadowlands/TheaterOfPain/Gorechop.lua
Shadowlands/TheaterOfPain/Options/Sounds.lua
Shadowlands/TheaterOfPain/Trash.lua

- 30s respawn
- Tenderizing Smash is Mythic-only, don't show initial CD bar in other difficulties.
- Meat Hook timer shouldn't show up if the encounter has ended
- Gorechop Trash: Tanks don't care if Chop is on them

Shadowlands/TheaterOfPain: Gorechop respawn timer, bug fixes

---

Shadowlands/MistsOfTirnaScithe/IngraMaloch.lua

According to the August 9, 2021,
"The duration of Droman's Wrath has been increased to 15 seconds (was 12 seconds)"
So a small fix to the bar duration was required.

 Shadowlands/MistsOfTirnaScithe/IngraMaloch: Fix wrath timer

---

Shadowlands/Plaguefall/DoctorIckus.lua

He leaps at 66% and 33% health, not on a timer.

Shadowlands/Plaguefall/DoctorIckus: Remove leap CD Bar

---

Shadowlands/SanguineDepths/Options/Colors.lua
Shadowlands/SanguineDepths/Options/Sounds.lua
Shadowlands/SanguineDepths/Tarvold.lua

Alerts for Residue under the player.
Also fixes the icon (and description in Options) for Coalesce Manifestation and takes advantage of the fact that boss frames were added to this fight.

Shadowlands/SanguineDepths/Tarvold: Residue damage, Coalesce Manifestation icon

---

BfA/KingsRest/Trash.lua

Fixes:
`BfA/KingsRest/Trash.lua:619: Invalid localeString! func=mod:PeriodicDamage, key=args.spellId, localeString=args.spellId == 270503 and "near" or "underyou", text=nil`

BfA/KingsRest/Trash: Tweak periodic damage logic

---

Legion/Karazhan/Curator.lua
Legion/Karazhan/Options/Sounds.lua

- Timer updates (including M+ differences from Mythic/Heroic)
- Sometimes Evocation is double-cast after ~1s, ensure alerts don't spam and timers remain accurate

Legion/Karazhan/Curator: Fix Evocation timers/alerts

---

WoD/IronDocks/Enforcers.lua
WoD/IronDocks/Options/Colors.lua
WoD/IronDocks/Options/Sounds.lua

In the dungeon journal it's Lava Sweep. The actual ability cast by the boss is Lava Swipe which has typos in the description. Changing the option key to match the dungeon journal.

WoD/IronDocks/Enforcers: Fix ability name/description

---

Legion/Karazhan/OperaWestfall.lua

Sep 1 hotfix notes:
> Increased the cooldown on Toe Knee's Dashing Flame Gale to 35 seconds (was 20 seconds).

Legion/Karazhan/OperaWestfall: Dashing Flame Gale timer update

---

WoD/IronDocks/Options/Colors.lua
WoD/IronDocks/Options/Sounds.lua
WoD/IronDocks/Trash.lua

This ability is instantly recast if stunned.

WoD/IronDocks/Trash: Remove unnecessary Flaming Arrows alert

---

WoD/IronDocks/Nokgar.lua

The event currently used can get spammed if there are multiple people in the group, revert back to UNIT_SPELLCAST_SUCCEEDED to prevent it.

WoD/IronDocks/Nokgar: Spam control on Shredding Swipes

---

Dragonflight/RubyLifePools/MelidrussaChillworn.lua

- Now stuns at 10 instead of 5
- Can now be dispelled by movement-dispelling effects

Dragonflight/RubyLifePools/MelidrussaChillworn: Primal Chill updates

---

Legion/Karazhan/Curator.lua

It seems with 10.0 Blizzard adjusted how much Mana Curator loses every second in M+ from 18/second to 13/second. This results in ~40% longer stage 1s.

Legion/Karazhan/Curator: Evocation timer update

---

Legion/Karazhan/Curator.lua

Due to yet another hotfix, reverts timer changes from #811 and #813.

Legion/Karazhan/Curator: Evocation timer updates

---

Legion/HallsOfValor/Odyn.lua

haven't tested non mythic but I can confirm that it's the other way around in mythic / mythic+
see https://youtu.be/k-9UXSHPrEM?t=1877

fix radiant tempest timer for m+

---

TBC/OldHillsbradFoothills/Trash.lua
WotLK/TheCullingOfStratholme/Trash.lua

In WotLK Classic patch 3.4.1 Blizzard has updated many of their APIs to parity with changes made in 10.0.2 for Dragonflight. BigWigs classic will need updates as well to account for this.
https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes
Fixes #871, but there will be errors later on until BigWigs is updated as well.

Update gossip APIs for WotLK

---

Dragonflight/AlgetharAcademy/EchoOfDoragosa.lua

the timer previously tracked the cast that you have to run out of instead of the "pull in" mechanic.
e.g pull in happens -> cast that you run out of.
tracking the pull instead allows players to use alter time or similar to avoid being pulled it.
also the timers were off for anything past the first timer

improve power vacuum timers

---

WotLK/TheCullingOfStratholme/Trash.lua

Currently, the Autoskip option in Culling of Stratholme will select the option of going through the roleplay. This fixes the selection so that the correct/skip option is picked as intended.

Fix roleplay skip in Culling of Strat

---

Shadowlands/TheNecroticWake/Trash.lua

This commit adds the Zolramus's Sorcerer cast: Shadow Well to the nameplates.
This spell leaves a lasting high damaging zone on the ground at the location of the tank. It's a good ability to track.
The spell should be casted by the Sorcerer every 13.6 seconds after each successful cast, it does get cast roughly 10 seconds into the fight initially though and I wasn't able to figure out if the Nameplate's support preplacing spell cd's on getting in combat yet, if that is an option in the current API already then I will adjust my pull request to do this from the start.

Add Zolramus Sorcerer's ShadowWell to nameplates
