- Legion/CourtOfStars/AdvisorMelandrus.lua
- Legion/CourtOfStars/PatrolCaptainGerdo.lua
- Legion/CourtOfStars/TalixaeFlamewreath.lua
- modules.xml
Very basic. Note: No timer data.
> Add Court of Stars

- LittleWigs.toc
- MoP/BlackTempleSolo/Locales/zhCN.lua
- MoP/BlackTempleSolo/Locales/zhTW.lua
- MoP/MogushanPalace/Locales/zhCN.lua
- MoP/ScarletHalls/Locales/zhCN.lua
- MoP/ScarletMonastery/Locales/zhCN.lua
- MoP/ShadoPanMonastery/Locales/zhCN.lua
- MoP/TempleOfTheJadeSerpent/Locales/zhCN.lua
- WoD/Auchindoun/Locales/zhCN.lua
- WoD/UpperBlackrockSpire/Locales/zhCN.lua
> zhCN/zhTW update.

- Legion/Karazhan/MaidenOfVirtue.lua
> Karazhan/MaidenOfVirtue: target scan for Sacred Ground

- Legion/CourtOfStars/Trash.lua
- Legion/CourtOfStars/modules.xml
These are the most important CoS spells.
> Added timers for Court of Stars trash

- Legion/BlackRookHold/Trash.lua
- Legion/EyeOfAzshara/Trash.lua
- Legion/EyeOfAzshara/modules.xml
- Legion/NeltharionsLair/Trash.lua
- Legion/TheArcway/Trash.lua
Adds several trash abilities as described in issue: https://github.com/BigWigsMods/LittleWigs/issues/15
> Add important trash abilities

- Legion/ArtifactScenarios/LordErdrisThorn.lua
- Legion/ArtifactScenarios/modules.xml
- LittleWigs.toc
> Add Healer Mage Tower Challenge

- Legion/DarkheartThicket/Trash.lua
- Legion/DarkheartThicket/modules.xml
- Legion/TheArcway/Trash.lua
> add darkheart thicket trash module

- Legion/CourtOfStars/Locales/zhTW.lua
Update CourtOfStars zhTW translation
> Update zhTW (CourtOfStars)

- Legion/CathedralOfEternalNight/Locales/zhTW.lua
> Update zhTW.lua (CathedralOfEternalNight)

- Legion/CourtOfStars/Locales/zhTW.lua
fix bad translates.
have problem for "%s" in line 38.39
> Update zhTW.lua (CourtOfStars)

- Legion/VaultOfTheWardens/Locales/zhTW.lua
> Update zhTW.lua (VaultOfTheWardens)

- Legion/VaultOfTheWardens/Tormentorum.lua
> VaultOfTheWardens/Tormentorum: add Seed of Corruption and Frightening Shout

- Legion/Karazhan/Moroes.lua
> Karazhan/Moroes: warn a healer about Coat Check too

- Legion/NeltharionsLair/UlaroggCragshaper.lua
> NeltharionsLair/UlaroggCragshaper: added a CD bar for the first cast of Sunder and fixed Stance of the Mountain, closes #11

- Legion/EyeOfAzshara/WarlordParjesh.lua
> EyeOfAzshara/WarlordParjesh: add Crashing Wave, closes #153

- Legion/DarkheartThicket/Oakheart.lua
> DarkheartThicket/Oakheart: added "Shattered Earth", closes #165

- Legion/SeatOfTheTriumvirate/ViceroyNezhar.lua
- adjusted CD bars for "Howling Dark" and spawns of Umbral Tentacles
- fixed the message for "Summon Ethereal Guards" not showing up
- combined "Summon Ethereal Guards" and "Dark Bulwark" in the settings
- added a CD bar for 2nd and further casts of "Summon Ethereal Guards"
- made the infobox look better when there are no Umbral Tentacles alive during the "Dark Bulwark" phase
> SeatOfTheTriumvirate/ViceroyNezhar: Various fixes & additions

- Legion/DarkheartThicket/Locales/deDE.lua
- Legion/DarkheartThicket/Locales/esES.lua
- Legion/DarkheartThicket/Locales/frFR.lua
- Legion/DarkheartThicket/Locales/itIT.lua
- Legion/DarkheartThicket/Locales/koKR.lua
- Legion/DarkheartThicket/Locales/ptBR.lua
- Legion/DarkheartThicket/Locales/ruRU.lua
- Legion/DarkheartThicket/Locales/zhCN.lua
- Legion/DarkheartThicket/Locales/zhTW.lua
- Legion/DarkheartThicket/Trash.lua
`:Blood()` was identical to `:Casts()`, that's why I moved "Blood Assault" there.
>  DarkheartThicket/Trash: added a warning for "Nightmare Toxin", fixed "Blood Bomb"

- Legion/EyeOfAzshara/Locales/deDE.lua
- Legion/EyeOfAzshara/Locales/esES.lua
- Legion/EyeOfAzshara/Locales/frFR.lua
- Legion/EyeOfAzshara/Locales/itIT.lua
- Legion/EyeOfAzshara/Locales/koKR.lua
- Legion/EyeOfAzshara/Locales/ptBR.lua
- Legion/EyeOfAzshara/Locales/ruRU.lua
- Legion/EyeOfAzshara/Locales/zhCN.lua
- Legion/EyeOfAzshara/Locales/zhTW.lua
- Legion/EyeOfAzshara/Trash.lua
Two colons in `:TargetMessage`'s "Polymorph: Fish: *playername*" bugged me :S.
> EyeOfAzshara/Trash: added a warning for "Thundering Stomp" and made the message for "Polymorph: Fish" shorter

- Legion/HallsOfValor/God-KingSkovald.lua
- Legion/HallsOfValor/Locales/deDE.lua
- Legion/HallsOfValor/Locales/esES.lua
- Legion/HallsOfValor/Locales/frFR.lua
- Legion/HallsOfValor/Locales/itIT.lua
- Legion/HallsOfValor/Locales/koKR.lua
- Legion/HallsOfValor/Locales/ptBR.lua
- Legion/HallsOfValor/Locales/ruRU.lua
- Legion/HallsOfValor/Locales/zhCN.lua
- Legion/HallsOfValor/Locales/zhTW.lua
- Legion/HallsOfValor/Odyn.lua
If you wipe on Skovald, to pull him again you need to first pick up the shield, which then triggers a short version of the roleplay consisting only of that phrase.
> HallsOfValor: added an additional trigger for Skovald's warmup timer, added a warmup timer for Odyn's gossip

- Legion/CourtOfStars/Locales/frFR.lua
Hi,
My first little PR on this project :) 
To fix one translation in Court of Stars, that's bugging me for a few weeks.
Thanks!
> Legion/CourtOfStars/Trash: Fix frFR translation for one of the hints

- BfA/TheMotherlode/CrowdPummeler.lua
- BfA/TheMotherlode/Rixxa.lua
- BfA/TheMotherlode/CrowdPummler: Add Blazing Azerite stack count to bar
- BfA/TheMotherlode/Rixxa: Fix Propellant Blast timer and add target message
> BfA/TheMotherlode: Boss improvements

- BfA/TheMotherlode/Options/Colors.lua
- BfA/TheMotherlode/Options/Sounds.lua
- BfA/TheMotherlode/Tikali.lua
> BfA/TheMotherlode/Tikali: Add Tectonic Smash

- BfA/Freehold/Kragg.lua
> BfA/Freehold/Kragg: Add Vile Bombardment

- BfA/TolDagor/Howlis.lua
- BfA/TolDagor/Korgus.lua
- BfA/TolDagor/Options/Colors.lua
- BfA/TolDagor/Options/Sounds.lua
Howlis:
- Add Viscious Mauling target message
Korgus:
- Add stack message and different sound when the target of Deadeye already has a stack
> BfA/TolDagor: Add Viscious Mauling and Deadeye stack message

- BfA/SiegeOfBoralus/Locales/zhCN.lua
- BfA/SiegeOfBoralus/Locales/zhTW.lua
> Update zhTW/zhCN translate 

- BfA/AtalDazar/Trash.lua
- BfA/Freehold/Booty.lua
- BfA/Freehold/Captains.lua
- BfA/KingsRest/Council.lua
- BfA/ShrineOfTheStorm/Aqusirr.lua
- BfA/ShrineOfTheStorm/Stormsong.lua
- BfA/SiegeOfBoralus/Lockwood.lua
- BfA/TempleOfSethraliss/Trash.lua
- BfA/TheMotherlode/Razzdunk.lua
- BfA/WaycrestManor/Heartsbane.lua
- BfA/WaycrestManor/Trash.lua
Also:
KingsRest/Council: Always play the barrel through sound even if it's not on you
> BfA: Add player arg to all PlaySound calls with a target

- BfA/Mechagon/KUJ0.lua
- Update timers for July 23 hotfixes
- Add Blazing Chomp timer
> BfA/Mechagon/KUJ0: Update timers

- BfA/TheMotherlode/Trash.lua
Throttle Activate Mech, Earth Shield, and Mining Charge
Remove interrupt voice from Activate Mech
> BfA/TheMotherlode/Trash: Add Rock Lance and throttle spells

- BfA/Freehold/Captains.lua
> BfA/Freehold/Captains: Fix initial timers sometimes being started too early

- BfA/TheMotherlode/Locales/deDE.lua
- BfA/TheMotherlode/Locales/esES.lua
- BfA/TheMotherlode/Locales/frFR.lua
- BfA/TheMotherlode/Locales/itIT.lua
- BfA/TheMotherlode/Locales/koKR.lua
- BfA/TheMotherlode/Locales/ptBR.lua
- BfA/TheMotherlode/Locales/ruRU.lua
- BfA/TheMotherlode/Locales/zhCN.lua
- BfA/TheMotherlode/Locales/zhTW.lua
- BfA/TheMotherlode/Trash.lua
Requires BigWigsMods/BigWigs#719
> BfA/TheMotherlode/Trash: Add Mechanized Peacekeeper

- BfA/Freehold/Trash.lua
Requires BigWigsMods/BigWigs#719
> BfA/Freehold/Trash: Add Boulder Throw nameplate bar

- Shadowlands/TheNecroticWake/Locales/deDE.lua
- Shadowlands/TheNecroticWake/Locales/esES.lua
- Shadowlands/TheNecroticWake/Locales/frFR.lua
- Shadowlands/TheNecroticWake/Locales/itIT.lua
- Shadowlands/TheNecroticWake/Locales/koKR.lua
- Shadowlands/TheNecroticWake/Locales/ptBR.lua
- Shadowlands/TheNecroticWake/Locales/ruRU.lua
- Shadowlands/TheNecroticWake/Locales/zhCN.lua
- Shadowlands/TheNecroticWake/Locales/zhTW.lua
- Shadowlands/TheNecroticWake/Options/Colors.lua
- Shadowlands/TheNecroticWake/Options/Sounds.lua
- Shadowlands/TheNecroticWake/Trash.lua
- Shadowlands/TheNecroticWake/modules.xml
> Shadowlands/TheNecroticWake: Add a module for trash

- Shadowlands/TheaterOfPain/Trash.lua
- Shadowlands/TheaterOfPain/modules.xml
Hey,
There are a few changes that enable ToP Trash module and add some alerts.
> Shadowlands/TheaterOfPain: Enable Trash module

- Shadowlands/SpiresOfAscension/Locales/deDE.lua
- Shadowlands/SpiresOfAscension/Locales/esES.lua
- Shadowlands/SpiresOfAscension/Locales/frFR.lua
- Shadowlands/SpiresOfAscension/Locales/itIT.lua
- Shadowlands/SpiresOfAscension/Locales/koKR.lua
- Shadowlands/SpiresOfAscension/Locales/ptBR.lua
- Shadowlands/SpiresOfAscension/Locales/ruRU.lua
- Shadowlands/SpiresOfAscension/Locales/zhCN.lua
- Shadowlands/SpiresOfAscension/Locales/zhTW.lua
- Shadowlands/SpiresOfAscension/Options/Colors.lua
- Shadowlands/SpiresOfAscension/Options/Sounds.lua
- Shadowlands/SpiresOfAscension/Oryphrion.lua
- Shadowlands/SpiresOfAscension/modules.xml
> Shadowlands/SpiresOfAscension/Oryphrion: Replace timers for "Drained" with energy-based warnings

- LittleWigs.toc
- Shadowlands/TazaveshTheVeiledMarket/Hylbrande.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/deDE.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/esES.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/frFR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/itIT.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/koKR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/locales.xml
- Shadowlands/TazaveshTheVeiledMarket/Locales/ptBR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/ruRU.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/zhCN.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/zhTW.lua
- Shadowlands/TazaveshTheVeiledMarket/MailroomMayhem.lua
- Shadowlands/TazaveshTheVeiledMarket/MyzasOasis.lua
- Shadowlands/TazaveshTheVeiledMarket/Options/Colors.lua
- Shadowlands/TazaveshTheVeiledMarket/Options/Sounds.lua
- Shadowlands/TazaveshTheVeiledMarket/Options/options.xml
- Shadowlands/TazaveshTheVeiledMarket/Soazmi.lua
- Shadowlands/TazaveshTheVeiledMarket/Soleah.lua
- Shadowlands/TazaveshTheVeiledMarket/TheGrandMenagerie.lua
- Shadowlands/TazaveshTheVeiledMarket/TimecapnHooktail.lua
- Shadowlands/TazaveshTheVeiledMarket/Zophex.lua
- Shadowlands/TazaveshTheVeiledMarket/modules.xml
- Shadowlands/modules.xml
Missing a few timers still but I don't have enough logs. I'll add them in after the dungeon is live.
> Shadowlands: Add Tazavesh, the Veiled Market

- Shadowlands/TheaterOfPain/Trash.lua
> Add Nefarious Darkspeaker's Death Winds

- Shadowlands/TazaveshTheVeiledMarket/Options/Sounds.lua
Forgot to re-run gen_option_values.lua
> Shadowlands/TazaveshTheVeiledMarket: Update option files

- Shadowlands/DeOtherSide/Options/Colors.lua
- Shadowlands/DeOtherSide/Options/Sounds.lua
- Shadowlands/DeOtherSide/Trash.lua
Alerts when the player is standing in the Reaver voidzone.
> Shadowlands/DeOtherSide/Trash: Add warning for Reaver

- Shadowlands/DeOtherSide/Options/Colors.lua
- Shadowlands/DeOtherSide/Options/Sounds.lua
- Shadowlands/DeOtherSide/TheManastorms.lua
- Shadowlands/DeOtherSide/Trash.lua
The Manastorms
- Track stages
- Track Shadowfury
- Track Diabolical Dooooooom
- Many timers
Fixes #637
> Shadowlands/DeOtherSide/TheManastorms: Add Shadowfury & Diabolical Doooom

- Shadowlands/TheNecroticWake/Locales/deDE.lua
- Shadowlands/TheNecroticWake/Locales/esES.lua
- Shadowlands/TheNecroticWake/Locales/frFR.lua
- Shadowlands/TheNecroticWake/Locales/itIT.lua
- Shadowlands/TheNecroticWake/Locales/koKR.lua
- Shadowlands/TheNecroticWake/Locales/ptBR.lua
- Shadowlands/TheNecroticWake/Locales/ruRU.lua
- Shadowlands/TheNecroticWake/Locales/zhCN.lua
- Shadowlands/TheNecroticWake/Locales/zhTW.lua
- Shadowlands/TheNecroticWake/Options/Colors.lua
- Shadowlands/TheNecroticWake/Options/Sounds.lua
- Shadowlands/TheNecroticWake/Trash.lua
- Track Animate Dead (stunnable channel which summons 3 adds)
- Track Final Bargain (stunnable full heal) (fixes #594)
- Track Boneshatter Shield (fixes #582)
> Shadowlands/TheNecroticWake/Trash: Animate Dead, Final Bargain, Boneshatter Shield

- Shadowlands/Plaguefall/DoctorIckus.lua
> Shadowlands/Plaguefall/DoctorIckus: Alert tank on slime injection cast

- Shadowlands/Plaguefall/DominaVenomblade.lua
- Shadowlands/Plaguefall/Options/Colors.lua
- Shadowlands/Plaguefall/Options/Sounds.lua
- Web Wrap alarm when applied to a player
- Web Wrap info when removed from that player
- Respawn is 30s
> Shadowlands/Plaguefall/DominaVenomblade: Web Wrap, respawn timer

- Shadowlands/TazaveshTheVeiledMarket/Locales/deDE.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/esES.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/esMX.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/frFR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/itIT.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/koKR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/ptBR.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/ruRU.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/zhCN.lua
- Shadowlands/TazaveshTheVeiledMarket/Locales/zhTW.lua
- Shadowlands/TazaveshTheVeiledMarket/Trash.lua
Adds timers for:
- Invigorating Fish Stick on pull and CD
- Tidal Stomp CD
- Blood in the Water (one-shot from standing in water)
> Shadowlands/TazaveshTheVeiledMarket/Trash: Timers for Fish Sticks, Tidal Stomp, Blood in the Water

- Shadowlands/TheaterOfPain/Locales/deDE.lua
- Shadowlands/TheaterOfPain/Locales/esES.lua
- Shadowlands/TheaterOfPain/Locales/frFR.lua
- Shadowlands/TheaterOfPain/Locales/itIT.lua
- Shadowlands/TheaterOfPain/Locales/koKR.lua
- Shadowlands/TheaterOfPain/Locales/ptBR.lua
- Shadowlands/TheaterOfPain/Locales/ruRU.lua
- Shadowlands/TheaterOfPain/Locales/zhCN.lua
- Shadowlands/TheaterOfPain/Locales/zhTW.lua
- Shadowlands/TheaterOfPain/Mordretha.lua
- Shadowlands/TheaterOfPain/Options/Colors.lua
- Shadowlands/TheaterOfPain/Options/Sounds.lua
- Shadowlands/TheaterOfPain/Trash.lua
> Shadowlands/TheaterOfPain/Mordretha: Death Grasp, respawn timer, warmup timer

- Shadowlands/TazaveshTheVeiledMarket/Options/Colors.lua
- Shadowlands/TazaveshTheVeiledMarket/Options/Sounds.lua
- Shadowlands/TazaveshTheVeiledMarket/Trash.lua
- Radiant Pulse alert
- Radiant Pulse CD timer
- Empowered Glyph of Restraint timer
- Throttle Hyperlight Bomb alert
- Fix Hyperlight Backhand scoping options
- Fix Power Kick scoping options
> Shadowlands/TazaveshTheVeiledMarket/Trash: Radiant Pulse, Empowered Glyph of Restraint, Bug fixes

- Shadowlands/HallsOfAtonement/Halkias.lua
Fixes #672.
Also tracks application of the non-mythic version of the fear.
> Shadowlands/HallsOfAtonement/Halkias: Update timers, respawn time

- Dragonflight/BrackenhideHollow/HackclawsWarBand.lua
- Dragonflight/HallsOfInfusion/GulpingGoliath.lua
- Dragonflight/HallsOfInfusion/KhajinTheUnyielding.lua
- Dragonflight/HallsOfInfusion/PrimalTsunami.lua
- Dragonflight/RubyLifePools/modules.xml
- Dragonflight/TazalgethAcademy/AccidentalAmalgamation.lua
- Dragonflight/TazalgethAcademy/EchoOfHeadteacherDoragosa.lua
- Dragonflight/TazalgethAcademy/HeadmasterDoragosa.lua
- Dragonflight/TazalgethAcademy/Vexamus.lua
- Dragonflight/TazalgethAcademy/modules.xml
- Dragonflight/TheAzureVault/TelashGreywing.lua
- Dragonflight/TheAzureVault/Umbrelskul.lua
- Dragonflight/UldamanLegacyOfTyr/TheLostDwarves.lua
Updates from build 10.0.0.44795
> Dragonflight: Updates

- WoD/GrimrailDepot/Locales/deDE.lua
- WoD/GrimrailDepot/Locales/esES.lua
- WoD/GrimrailDepot/Locales/frFR.lua
- WoD/GrimrailDepot/Locales/itIT.lua
- WoD/GrimrailDepot/Locales/koKR.lua
- WoD/GrimrailDepot/Locales/ptBR.lua
- WoD/GrimrailDepot/Locales/ruRU.lua
- WoD/GrimrailDepot/Locales/zhCN.lua
- WoD/GrimrailDepot/Locales/zhTW.lua
- WoD/GrimrailDepot/Options/Colors.lua
- WoD/GrimrailDepot/Options/Sounds.lua
- WoD/GrimrailDepot/Rocketspark.lua
Timers and alerts for:
- X21-01A Missile Barrage
- Recovering
- Better Position
- VX18-B Target Eliminator
Alerts for:
- New Plan!
- Unmanaged Aggression
> WoD/GrimrailDepot/Rocketspark: Rework timers, track missing abilities

- Legion/Karazhan/ManaDevourer.lua
- Legion/Karazhan/Options/Colors.lua
- Legion/Karazhan/Options/Sounds.lua
> Legion/Karazhan/ManaDevourer: Energy Discharge, timers, respawn

- Legion/Karazhan/Options/Colors.lua
- Legion/Karazhan/Options/Sounds.lua
- Legion/Karazhan/ShadeOfMedivh.lua
- Piercing Missiles now has sound for the tank
- More accurate Focused Power timer
- Ceaseless Winter duration was started 3s early and ended 3s early
> Legion/Karazhan/ShadeOfMedivh: Piercing Missiles alert, timer updates

- Dragonflight/BrackenhideHollow/Locales/deDE.lua
- Dragonflight/BrackenhideHollow/Locales/esES.lua
- Dragonflight/BrackenhideHollow/Locales/frFR.lua
- Dragonflight/BrackenhideHollow/Locales/itIT.lua
- Dragonflight/BrackenhideHollow/Locales/koKR.lua
- Dragonflight/BrackenhideHollow/Locales/ptBR.lua
- Dragonflight/BrackenhideHollow/Locales/ruRU.lua
- Dragonflight/BrackenhideHollow/Locales/zhCN.lua
- Dragonflight/BrackenhideHollow/Locales/zhTW.lua
- Dragonflight/BrackenhideHollow/Options/Colors.lua
- Dragonflight/BrackenhideHollow/Options/Sounds.lua
- Dragonflight/BrackenhideHollow/Trash.lua
Just the two most important trash abilities for now.
> Dragonflight/BrackenhideHollow/Trash: Add trash module

- WoD/IronDocks/Options/Colors.lua
- WoD/IronDocks/Options/Sounds.lua
- WoD/IronDocks/Trash.lua
> WoD/IronDocks/Trash: Don't track Flaming Arrows

- Legion/CourtOfStars/AdvisorMelandrus.lua
it does increasing damage so it's useful to have a counter for it to plan cds
> add counter to slicingMaelstrom

- Dragonflight/DawnOfTheInfinite/BlightOfGalakrond.lua
not sure about the way I named/structured certain things, feel free to edit.
> Dragonflight/DawnOfTheInfinite/BlightOfGalakrond: timer updates

- BfA/SiegeOfBoralus/Trash.lua
1. Add Iron Ambush CD bar and Nameplate of Riptide Shredder
2. Add Shattering Bellow CD bar of Scrimshaw Enforcer
3. Add Savage Tempest CD bar of Irontide Raider
> Update Trash timer of SiegeOfBoralus

- Classic/!Locales/esES.lua
- WarWithin/!Locales/esES.lua
Ve'nari says that when the first boss warmup starts
> Update locale esES
